name: gradle
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Set up JDK 8
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 8
          distribution: zulu
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload build JARs
        uses: actions/upload-artifact@v4.3.3
        with:
          name: build-jars
          path: build/libs/*